/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RENT;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rishu
 */
   
public class Payment extends javax.swing.JFrame {
  Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    /**
     * Creates new form Payment
     */
    
    public Payment() {
        
        
        initComponents();
   
        conn =javaconnet.ConnectDb();
    }
     public Payment(String msg) {
        
               // conn =javaconnet.ConnectDb();
        initComponents();
        Txtamount.setText(msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Txtname = new javax.swing.JTextField();
        Txtnum = new javax.swing.JTextField();
        Txtcvv = new javax.swing.JPasswordField();
        Txtmonth = new javax.swing.JComboBox<>();
        Txtyear = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Txtamount = new javax.swing.JLabel();
        Proceed = new javax.swing.JButton();
        Generate = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1372, 891));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 60));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 254, 224));
        jLabel2.setText("Debit / Credit Card Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 30, 490, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enter Your Name as on Card :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 140, 250, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Enter Card Number :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 200, 170, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Enter CVV : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 320, 110, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Exp  Month:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 254, 130, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Exp Year:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 260, 110, 30);

        Txtname.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnameActionPerformed(evt);
            }
        });
        Txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtnameKeyPressed(evt);
            }
        });
        jPanel1.add(Txtname);
        Txtname.setBounds(420, 140, 240, 30);

        Txtnum.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Txtnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtnumKeyPressed(evt);
            }
        });
        jPanel1.add(Txtnum);
        Txtnum.setBounds(420, 200, 240, 30);

        Txtcvv.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Txtcvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcvvActionPerformed(evt);
            }
        });
        Txtcvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtcvvKeyPressed(evt);
            }
        });
        jPanel1.add(Txtcvv);
        Txtcvv.setBounds(420, 320, 150, 30);

        Txtmonth.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Txtmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(Txtmonth);
        Txtmonth.setBounds(230, 255, 100, 30);

        Txtyear.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Txtyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", " ", " " }));
        jPanel1.add(Txtyear);
        Txtyear.setBounds(540, 260, 90, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("AMOUNT TO BE PAID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 380, 280, 40);

        Txtamount.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Txtamount.setForeground(new java.awt.Color(255, 255, 255));
        Txtamount.setText("jLabel8");
        jPanel1.add(Txtamount);
        Txtamount.setBounds(350, 380, 90, 30);

        Proceed.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Proceed.setText("Proceed To Pay");
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });
        jPanel1.add(Proceed);
        Proceed.setBounds(90, 440, 180, 40);

        Generate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Generate.setText("Generate Report");
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });
        jPanel1.add(Generate);
        Generate.setBounds(320, 440, 190, 40);

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(560, 440, 190, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(240, 90, 890, 550);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rishu\\Downloads\\Project Images\\Suggest.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1430, 775);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1430, 940);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnameActionPerformed

    private void TxtcvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtcvvActionPerformed

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed

      /* String nm=Txtname.getText();
        String num= Txtnum.getText();
        String mon= (String) Txtmonth.getSelectedItem();
        String yea= (String) Txtyear.getSelectedItem();
        String c= Txtcvv.getText();
        String amo= Txtamount.getText(); */

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost/Carrental","root","");
            // String sql= "Insert into payment(Name, Number, Month, Year,Cvv , Amount) values (?,?,?,?,?,?)";

            ps= conn.prepareStatement("Insert into payment(Name, Number, Month, Year,Cvv , Amount) values (?,?,?,?,?,?)");

            ps.setString(1,Txtname.getText());
            ps.setString(2,Txtnum.getText());
            ps.setString(3, (String) Txtmonth.getSelectedItem());
            ps.setString(4,(String) Txtyear.getSelectedItem());
            ps.setString(5,Txtcvv.getText());
            ps.setString(6,Txtamount.getText());

            ps.execute();

            JOptionPane.showMessageDialog(null, "Payment Succesfull !!");

            // TODO add your handling code here
        } catch (Exception ex) {
            //Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_ProceedActionPerformed

    private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed

Genrate g= new Genrate();
g.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked

        Usershome uh= new Usershome();
        uh.setAlwaysOnTop(true);
        int a= JOptionPane.showConfirmDialog(uh,"Do you want to exit??","Select", JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new Usershome().setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        /* Usershome uh = new Usershome();
        uh.setVisible(true);*/
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void TxtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtnameKeyPressed
         char c = evt.getKeyChar();
       if(Character.isLetter(c) || Character.isWhitespace(c) ||Character.isISOControl(c)){
            //contact.setEditable(false);
            //cnval.setText("Please enter number Only");
        }
       
        else{
            JOptionPane.showMessageDialog(null,"Only Letters are allowed");
                Txtname.setText("");
            }  // TODO add your handling code here:
    }//GEN-LAST:event_TxtnameKeyPressed

    private void TxtnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtnumKeyPressed
          char c = evt.getKeyChar();
       if(Character.isDigit(c)|| Character.isWhitespace(c) ||Character.isISOControl(c)){
            //contact.setEditable(false);
            //cnval.setText("Please enter number Only");
        }
       
        else{
            JOptionPane.showMessageDialog(null,"Only Numbers are allowed");
             Txtnum.setText("");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_TxtnumKeyPressed

    private void TxtcvvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtcvvKeyPressed
         char c = evt.getKeyChar();
       if(Character.isDigit(c)|| Character.isWhitespace(c) ||Character.isISOControl(c)){
            //contact.setEditable(false);
            //cnval.setText("Please enter number Only");
        }
       
        else{
            JOptionPane.showMessageDialog(null,"Only Numbers are allowed");
             Txtcvv.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_TxtcvvKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Generate;
    private javax.swing.JButton Proceed;
    private javax.swing.JLabel Txtamount;
    private javax.swing.JPasswordField Txtcvv;
    private javax.swing.JComboBox<String> Txtmonth;
    private javax.swing.JTextField Txtname;
    private javax.swing.JTextField Txtnum;
    private javax.swing.JComboBox<String> Txtyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
